# Generated by Django 4.0.6 on 2022-07-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=20)),
                ('ABO', models.CharField(max_length=2)),
                ('D', models.CharField(choices=[('P', 'Pos'), ('N', 'Neg'), ('?', 'NT')], default='Neg', max_length=1)),
                ('location', models.CharField(max_length=20)),
                ('shelf', models.IntegerField()),
            ],
        ),
    ]
