# Generated by Django 4.0.6 on 2022-07-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='D',
            field=models.CharField(choices=[('?', 'NT'), ('P', 'Pos'), ('N', 'Neg')], default='?', max_length=1),
        ),
    ]
