# Generated by Django 4.0.6 on 2022-07-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_unit_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='C',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Cw',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Dia',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Dib',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='E',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Fy3',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Fya',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Fyb',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Jk3',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Jka',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Jkb',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Jsa',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Jsb',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='K',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Kpa',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Kpb',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Lea',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Leb',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='M',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='N',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='S',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='U',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Wra',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='Wrb',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='c',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='e',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='k',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='s',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('+', 'Positive'), ('-', 'Negative')], default='NT', max_length=5),
        ),
    ]
