# Generated by Django 4.0.6 on 2022-07-13 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_unit_c_unit_cw_unit_dia_unit_dib_unit_e_unit_fy3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
