# Generated by Django 4.0.6 on 2022-07-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_unit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='notes',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
