# Generated by Django 4.0.6 on 2022-07-13 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_unit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expires'),
            preserve_default=False,
        ),
    ]
